"""
StealthHumanizer — Safe Synonym Database (500+ entries)
Ported from TypeScript lib/synonyms.ts → Python

Each word maps to a list of safe, context-appropriate synonyms.
Used by postprocess.py for 25%-probability word swaps.
"""

import random

SYNONYM_MAP: dict[str, list[str]] = {
    'important': ['significant', 'crucial', 'key', 'vital', 'essential'],
    'significant': ['important', 'notable', 'meaningful', 'considerable', 'substantial'],
    'crucial': ['important', 'key', 'critical', 'vital', 'essential'],
    'vital': ['important', 'crucial', 'essential', 'critical', 'key'],
    'essential': ['important', 'crucial', 'vital', 'necessary', 'key'],
    'critical': ['important', 'crucial', 'vital', 'key', 'essential'],
    'necessary': ['needed', 'required', 'essential', 'important', 'vital'],
    'required': ['needed', 'necessary', 'essential', 'mandatory', 'obligatory'],
    'key': ['important', 'crucial', 'vital', 'central', 'essential'],
    'central': ['key', 'core', 'main', 'primary', 'fundamental'],
    'primary': ['main', 'chief', 'principal', 'key', 'central'],
    'secondary': ['minor', 'lesser', 'secondary', 'supporting', 'auxiliary'],
    'major': ['significant', 'important', 'substantial', 'large', 'considerable'],
    'minor': ['small', 'lesser', 'secondary', 'slight', 'trivial'],
    'significant': ['important', 'notable', 'meaningful', 'considerable', 'substantial'],
    'considerable': ['significant', 'substantial', 'large', 'notable', 'meaningful'],
    'substantial': ['considerable', 'significant', 'large', 'meaningful', 'notable'],
    'notable': ['significant', 'important', 'remarkable', 'outstanding', 'noteworthy'],
    'numerous': ['many', 'several', 'countless', 'multiple', 'various'],
    'various': ['different', 'diverse', 'multiple', 'several', 'numerous'],
    'diverse': ['various', 'different', 'varied', 'multiple', 'wide-ranging'],
    'multiple': ['several', 'various', 'many', 'numerous', 'different'],
    'several': ['multiple', 'various', 'many', 'numerous', 'a few'],
    'different': ['various', 'diverse', 'distinct', 'separate', 'alternative'],
    'similar': ['comparable', 'akin', 'related', 'analogous', 'like'],
    'comparable': ['similar', 'equivalent', 'analogous', 'like', 'parallel'],
    'alternative': ['different', 'other', 'substitute', 'option', 'choice'],
    'additional': ['extra', 'more', 'further', 'supplementary', 'added'],
    'further': ['additional', 'more', 'extra', 'continued', 'extended'],
    'additional': ['extra', 'more', 'further', 'supplementary', 'other'],
    'effective': ['successful', 'efficient', 'productive', 'powerful', 'impactful'],
    'efficient': ['effective', 'productive', 'streamlined', 'organized', 'capable'],
    'successful': ['effective', 'accomplished', 'productive', 'thriving', 'fruitful'],
    'productive': ['effective', 'efficient', 'fruitful', 'successful', 'constructive'],
    'powerful': ['strong', 'impactful', 'effective', 'potent', 'influential'],
    'impactful': ['powerful', 'effective', 'meaningful', 'significant', 'influential'],
    'influential': ['powerful', 'important', 'significant', 'impactful', 'prominent'],
    'prominent': ['important', 'notable', 'significant', 'outstanding', 'leading'],
    'outstanding': ['excellent', 'exceptional', 'notable', 'impressive', 'remarkable'],
    'remarkable': ['outstanding', 'notable', 'impressive', 'extraordinary', 'striking'],
    'impressive': ['outstanding', 'remarkable', 'notable', 'striking', 'impressive'],
    'exceptional': ['outstanding', 'remarkable', 'extraordinary', 'unusual', 'rare'],
    'extraordinary': ['exceptional', 'remarkable', 'outstanding', 'unusual', 'special'],
    'unusual': ['rare', 'exceptional', 'uncommon', 'extraordinary', 'atypical'],
    'uncommon': ['rare', 'unusual', 'exceptional', 'atypical', 'infrequent'],
    'rare': ['uncommon', 'unusual', 'exceptional', 'scarce', 'infrequent'],
    'frequent': ['common', 'regular', 'recurring', 'repeated', 'consistent'],
    'consistent': ['regular', 'steady', 'reliable', 'uniform', 'constant'],
    'constant': ['steady', 'consistent', 'continuous', 'regular', 'ongoing'],
    'continuous': ['ongoing', 'constant', 'steady', 'uninterrupted', 'perpetual'],
    'ongoing': ['continuous', 'constant', 'current', 'active', 'proceeding'],
    'current': ['present', 'existing', 'ongoing', 'modern', 'contemporary'],
    'modern': ['current', 'contemporary', 'present', 'recent', 'updated'],
    'contemporary': ['modern', 'current', 'present', 'recent', 'today\'s'],
    'recent': ['current', 'latest', 'modern', 'new', 'fresh'],
    'latest': ['recent', 'current', 'new', 'updated', 'modern'],
    'updated': ['recent', 'current', 'modern', 'revised', 'improved'],
    'improved': ['better', 'enhanced', 'upgraded', 'refined', 'superior'],
    'enhanced': ['improved', 'better', 'upgraded', 'refined', 'strengthened'],
    'upgraded': ['improved', 'enhanced', 'better', 'advanced', 'superior'],
    'refined': ['improved', 'enhanced', 'polished', 'better', 'optimized'],
    'superior': ['better', 'improved', 'higher', 'advanced', 'enhanced'],
    'advanced': ['improved', 'superior', 'cutting-edge', 'modern', 'enhanced'],
    'innovative': ['new', 'creative', 'fresh', 'original', 'novel'],
    'creative': ['innovative', 'original', 'fresh', 'inventive', 'imaginative'],
    'original': ['creative', 'innovative', 'fresh', 'unique', 'novel'],
    'novel': ['original', 'innovative', 'fresh', 'new', 'unique'],
    'unique': ['distinctive', 'original', 'novel', 'special', 'one-of-a-kind'],
    'distinctive': ['unique', 'special', 'characteristic', 'particular', 'individual'],
    'particular': ['specific', 'certain', 'individual', 'distinct', 'particular'],
    'specific': ['particular', 'exact', 'precise', 'detailed', 'specific'],
    'precise': ['exact', 'specific', 'accurate', 'detailed', 'precise'],
    'accurate': ['precise', 'exact', 'correct', 'true', 'specific'],
    'exact': ['precise', 'accurate', 'specific', 'correct', 'true'],
    'correct': ['accurate', 'right', 'proper', 'true', 'valid'],
    'proper': ['correct', 'appropriate', 'right', 'suitable', 'fitting'],
    'appropriate': ['proper', 'suitable', 'fitting', 'right', 'correct'],
    'suitable': ['appropriate', 'proper', 'fitting', 'right', 'apt'],
    'fitting': ['suitable', 'appropriate', 'proper', 'right', 'apt'],
    'right': ['correct', 'proper', 'appropriate', 'suitable', 'fitting'],
    'wrong': ['incorrect', 'mistaken', 'erroneous', 'inaccurate', 'false'],
    'incorrect': ['wrong', 'mistaken', 'erroneous', 'inaccurate', 'false'],
    'mistaken': ['wrong', 'incorrect', 'erroneous', 'inaccurate', 'false'],
    'erroneous': ['incorrect', 'wrong', 'mistaken', 'inaccurate', 'false'],
    'false': ['incorrect', 'wrong', 'mistaken', 'erroneous', 'untrue'],
    'true': ['correct', 'accurate', 'real', 'genuine', 'actual'],
    'genuine': ['real', 'true', 'authentic', 'actual', 'sincere'],
    'authentic': ['genuine', 'real', 'true', 'actual', 'legitimate'],
    'actual': ['real', 'true', 'genuine', 'actual', 'factual'],
    'real': ['genuine', 'true', 'actual', 'authentic', 'legitimate'],
    'legitimate': ['genuine', 'authentic', 'valid', 'real', 'proper'],
    'valid': ['legitimate', 'proper', 'correct', 'sound', 'legitimate'],
    'sound': ['valid', 'solid', 'reliable', 'reasonable', 'logical'],
    'reliable': ['dependable', 'trustworthy', 'consistent', 'steady', 'solid'],
    'dependable': ['reliable', 'trustworthy', 'consistent', 'steady', 'solid'],
    'trustworthy': ['reliable', 'dependable', 'honest', 'credible', 'solid'],
    'solid': ['reliable', 'strong', 'dependable', 'sound', 'stable'],
    'stable': ['steady', 'solid', 'reliable', 'secure', 'consistent'],
    'secure': ['safe', 'stable', 'protected', 'reliable', 'strong'],
    'safe': ['secure', 'protected', 'reliable', 'stable', 'sound'],
    'protected': ['safe', 'secure', 'shielded', 'guarded', 'defended'],
    'strong': ['powerful', 'solid', 'sturdy', 'robust', 'tough'],
    'robust': ['strong', 'solid', 'sturdy', 'reliable', 'tough'],
    'sturdy': ['strong', 'solid', 'robust', 'tough', 'durable'],
    'tough': ['strong', 'sturdy', 'robust', 'durable', 'hardy'],
    'durable': ['sturdy', 'tough', 'long-lasting', 'robust', 'resilient'],
    'resilient': ['durable', 'tough', 'strong', 'adaptable', 'flexible'],
    'flexible': ['adaptable', 'versatile', 'adjustable', 'bendable', 'pliable'],
    'adaptable': ['flexible', 'versatile', 'adjustable', 'responsive', 'elastic'],
    'versatile': ['flexible', 'adaptable', 'multi-purpose', 'all-around', 'handy'],
    'adjustable': ['flexible', 'adaptable', 'variable', 'changeable', 'modifiable'],
    'responsive': ['adaptable', 'flexible', 'reactive', 'sensitive', 'quick'],
    'sensitive': ['responsive', 'delicate', 'aware', 'perceptive', 'subtle'],
    'subtle': ['delicate', 'nuanced', 'refined', 'gentle', 'soft'],
    'delicate': ['subtle', 'fine', 'gentle', 'soft', 'refined'],
    'gentle': ['soft', 'mild', 'delicate', 'tender', 'subtle'],
    'soft': ['gentle', 'mild', 'delicate', 'tender', 'smooth'],
    'smooth': ['even', 'flat', 'sleek', 'polished', 'seamless'],
    'polished': ['smooth', 'refined', 'finished', 'perfect', 'elegant'],
    'elegant': ['refined', 'polished', 'graceful', 'sophisticated', 'stylish'],
    'sophisticated': ['refined', 'elegant', 'advanced', 'complex', 'polished'],
    'complex': ['complicated', 'intricate', 'sophisticated', 'detailed', 'involved'],
    'complicated': ['complex', 'intricate', 'involved', 'difficult', 'detailed'],
    'intricate': ['complex', 'complicated', 'detailed', 'elaborate', 'involved'],
    'detailed': ['specific', 'thorough', 'comprehensive', 'elaborate', 'in-depth'],
    'thorough': ['detailed', 'comprehensive', 'complete', 'exhaustive', 'extensive'],
    'comprehensive': ['thorough', 'complete', 'extensive', 'detailed', 'full'],
    'complete': ['full', 'entire', 'comprehensive', 'thorough', 'whole'],
    'entire': ['complete', 'full', 'whole', 'total', 'absolute'],
    'full': ['complete', 'entire', 'whole', 'total', 'comprehensive'],
    'whole': ['complete', 'entire', 'full', 'total', 'entire'],
    'total': ['complete', 'entire', 'full', 'whole', 'absolute'],
    'absolute': ['total', 'complete', 'entire', 'full', 'unconditional'],
    'extensive': ['comprehensive', 'thorough', 'wide-ranging', 'broad', 'vast'],
    'broad': ['wide', 'extensive', 'comprehensive', 'general', 'sweeping'],
    'wide': ['broad', 'extensive', 'comprehensive', 'vast', 'large'],
    'vast': ['huge', 'enormous', 'massive', 'immense', 'extensive'],
    'huge': ['vast', 'enormous', 'massive', 'immense', 'large'],
    'enormous': ['vast', 'huge', 'massive', 'immense', 'gigantic'],
    'massive': ['huge', 'vast', 'enormous', 'immense', 'substantial'],
    'immense': ['vast', 'huge', 'enormous', 'massive', 'gigantic'],
    'large': ['big', 'substantial', 'considerable', 'significant', 'sizable'],
    'big': ['large', 'substantial', 'significant', 'considerable', 'major'],
    'small': ['little', 'minor', 'slight', 'modest', 'petite'],
    'little': ['small', 'minor', 'slight', 'modest', 'tiny'],
    'tiny': ['little', 'small', 'minute', 'miniature', 'micro'],
    'minute': ['tiny', 'small', 'little', 'micro', 'minute'],
    'slight': ['small', 'minor', 'little', 'modest', 'subtle'],
    'modest': ['small', 'slight', 'moderate', 'reasonable', 'humble'],
    'moderate': ['reasonable', 'modest', 'balanced', 'fair', 'temperate'],
    'reasonable': ['fair', 'moderate', 'sensible', 'rational', 'logical'],
    'fair': ['reasonable', 'just', 'equitable', 'balanced', 'impartial'],
    'balanced': ['moderate', 'reasonable', 'fair', 'stable', 'even'],
    'stable': ['steady', 'balanced', 'secure', 'reliable', 'consistent'],
    'steady': ['stable', 'consistent', 'reliable', 'constant', 'firm'],
    'firm': ['solid', 'steady', 'strong', 'secure', 'stable'],
    'secure': ['safe', 'stable', 'strong', 'protected', 'reliable'],
    'strong': ['powerful', 'solid', 'sturdy', 'robust', 'tough'],
    'weak': ['feeble', 'fragile', 'flimsy', 'delicate', 'vulnerable'],
    'vulnerable': ['weak', 'exposed', 'susceptible', 'fragile', 'at risk'],
    'exposed': ['vulnerable', 'unprotected', 'open', 'susceptible', 'visible'],
    'visible': ['obvious', 'apparent', 'noticeable', 'evident', 'clear'],
    'obvious': ['clear', 'apparent', 'evident', 'visible', 'plain'],
    'apparent': ['obvious', 'clear', 'evident', 'visible', 'noticeable'],
    'evident': ['obvious', 'clear', 'apparent', 'visible', 'noticeable'],
    'noticeable': ['obvious', 'visible', 'apparent', 'evident', 'clear'],
    'clear': ['obvious', 'apparent', 'evident', 'plain', 'visible'],
    'plain': ['clear', 'simple', 'obvious', 'straightforward', 'apparent'],
    'simple': ['easy', 'straightforward', 'basic', 'uncomplicated', 'plain'],
    'straightforward': ['simple', 'direct', 'clear', 'easy', 'uncomplicated'],
    'direct': ['straightforward', 'clear', 'simple', 'explicit', 'immediate'],
    'explicit': ['clear', 'direct', 'specific', 'exact', 'plain'],
    'immediate': ['direct', 'instant', 'prompt', 'quick', 'swift'],
    'quick': ['fast', 'swift', 'rapid', 'speedy', 'prompt'],
    'fast': ['quick', 'swift', 'rapid', 'speedy', 'prompt'],
    'swift': ['fast', 'quick', 'rapid', 'speedy', 'prompt'],
    'rapid': ['fast', 'quick', 'swift', 'speedy', 'prompt'],
    'speedy': ['fast', 'quick', 'swift', 'rapid', 'prompt'],
    'prompt': ['quick', 'swift', 'immediate', 'fast', 'ready'],
    'ready': ['prepared', 'set', 'available', 'willing', 'primed'],
    'prepared': ['ready', 'set', 'equipped', 'arranged', 'organized'],
    'organized': ['arranged', 'structured', 'systematic', 'ordered', 'coordinated'],
    'structured': ['organized', 'arranged', 'systematic', 'ordered', 'formatted'],
    'systematic': ['organized', 'structured', 'methodical', 'ordered', 'logical'],
    'methodical': ['systematic', 'organized', 'structured', 'ordered', 'logical'],
    'logical': ['rational', 'reasonable', 'systematic', 'sound', 'coherent'],
    'rational': ['logical', 'reasonable', 'sensible', 'sound', 'coherent'],
    'sensible': ['reasonable', 'rational', 'logical', 'practical', 'prudent'],
    'practical': ['sensible', 'realistic', 'useful', 'functional', 'pragmatic'],
    'realistic': ['practical', 'sensible', 'reasonable', 'grounded', 'feasible'],
    'feasible': ['practical', 'possible', 'realistic', 'achievable', 'viable'],
    'possible': ['feasible', 'achievable', 'practical', 'viable', 'attainable'],
    'achievable': ['possible', 'feasible', 'attainable', 'realistic', 'reachable'],
    'attainable': ['achievable', 'possible', 'feasible', 'reachable', 'realistic'],
    'viable': ['feasible', 'possible', 'practical', 'achievable', 'workable'],
    'workable': ['viable', 'feasible', 'practical', 'functional', 'operational'],
    'functional': ['operational', 'working', 'practical', 'useful', 'effective'],
    'operational': ['functional', 'working', 'active', 'running', 'operational'],
    'effective': ['successful', 'efficient', 'productive', 'powerful', 'impactful'],
    'successful': ['effective', 'accomplished', 'productive', 'thriving', 'fruitful'],
    'accomplished': ['successful', 'achieved', 'completed', 'fulfilled', 'realized'],
    'completed': ['finished', 'done', 'accomplished', 'concluded', 'fulfilled'],
    'finished': ['completed', 'done', 'concluded', 'accomplished', 'wrapped up'],
    'concluded': ['finished', 'completed', 'done', 'ended', 'wrapped up'],
    'achieved': ['accomplished', 'reached', 'attained', 'realized', 'fulfilled'],
    'reached': ['achieved', 'attained', 'arrived', 'gotten to', 'hit'],
    'attained': ['achieved', 'reached', 'accomplished', 'realized', 'fulfilled'],
    'realized': ['achieved', 'accomplished', 'fulfilled', 'attained', 'recognized'],
    'recognized': ['acknowledged', 'identified', 'spotted', 'noticed', 'seen'],
    'acknowledged': ['recognized', 'admitted', 'accepted', 'confirmed', 'noted'],
    'identified': ['recognized', 'spotted', 'found', 'detected', 'discovered'],
    'discovered': ['found', 'uncovered', 'revealed', 'detected', 'spotted'],
    'revealed': ['discovered', 'uncovered', 'exposed', 'shown', 'disclosed'],
    'exposed': ['revealed', 'uncovered', 'shown', 'displayed', 'disclosed'],
    'uncovered': ['discovered', 'revealed', 'exposed', 'found', 'brought to light'],
    'detected': ['spotted', 'identified', 'noticed', 'found', 'discovered'],
    'noticed': ['spotted', 'detected', 'observed', 'seen', 'recognized'],
    'observed': ['noticed', 'seen', 'spotted', 'detected', 'witnessed'],
    'witnessed': ['observed', 'seen', 'noticed', 'experienced', 'viewed'],
    'experienced': ['encountered', 'faced', 'lived through', 'went through', 'dealt with'],
    'encountered': ['faced', 'experienced', 'met with', 'run into', 'come across'],
    'faced': ['encountered', 'confronted', 'dealt with', 'tackled', 'addressed'],
    'confronted': ['faced', 'tackled', 'addressed', 'dealt with', 'handled'],
    'addressed': ['handled', 'dealt with', 'tackled', 'resolved', 'managed'],
    'handled': ['managed', 'dealt with', 'addressed', 'tackled', 'taken care of'],
    'managed': ['handled', 'dealt with', 'addressed', 'directed', 'oversaw'],
    'resolved': ['solved', 'settled', 'handled', 'addressed', 'fixed'],
    'solved': ['resolved', 'fixed', 'worked out', 'figured out', 'sorted out'],
    'fixed': ['solved', 'resolved', 'repaired', 'corrected', 'sorted out'],
    'corrected': ['fixed', 'adjusted', 'amended', 'revised', 'rectified'],
    'adjusted': ['modified', 'altered', 'changed', 'tweaked', 'adapted'],
    'modified': ['adjusted', 'altered', 'changed', 'adapted', 'tweaked'],
    'altered': ['changed', 'modified', 'adjusted', 'adapted', 'transformed'],
    'changed': ['altered', 'modified', 'adjusted', 'shifted', 'transformed'],
    'transformed': ['changed', 'converted', 'turned', 'altered', 'remade'],
    'converted': ['changed', 'transformed', 'turned', 'adapted', 'modified'],
    'shifted': ['moved', 'changed', 'transferred', 'relocated', 'adjusted'],
    'transferred': ['moved', 'shifted', 'relocated', 'passed', 'handed off'],
    'moved': ['shifted', 'transferred', 'relocated', 'changed', 'adjusted'],
    'relocated': ['moved', 'transferred', 'shifted', 'repositioned', 'moved'],
    'created': ['made', 'built', 'developed', 'established', 'formed'],
    'developed': ['created', 'built', 'established', 'formed', 'designed'],
    'established': ['created', 'founded', 'started', 'set up', 'formed'],
    'founded': ['started', 'established', 'created', 'launched', 'formed'],
    'started': ['began', 'launched', 'initiated', 'kicked off', 'started'],
    'launched': ['started', 'began', 'initiated', 'introduced', 'rolled out'],
    'initiated': ['started', 'began', 'launched', 'kicked off', 'triggered'],
    'introduced': ['launched', 'presented', 'rolled out', 'unveiled', 'debuted'],
    'presented': ['introduced', 'shown', 'displayed', 'offered', 'demonstrated'],
    'demonstrated': ['shown', 'proven', 'displayed', 'illustrated', 'exhibited'],
    'displayed': ['shown', 'exhibited', 'presented', 'revealed', 'demonstrated'],
    'exhibited': ['displayed', 'shown', 'presented', 'demonstrated', 'revealed'],
    'illustrated': ['demonstrated', 'shown', 'exemplified', 'depicted', 'explained'],
    'explained': ['described', 'clarified', 'illustrated', 'detailed', 'laid out'],
    'described': ['explained', 'detailed', 'outlined', 'depicted', 'characterized'],
    'detailed': ['described', 'explained', 'outlined', 'specified', 'laid out'],
    'outlined': ['described', 'detailed', 'summarized', 'sketched', 'mapped out'],
    'summarized': ['outlined', 'condensed', 'recapped', 'briefed', 'wrapped up'],
    'condensed': ['summarized', 'shortened', 'compressed', 'reduced', 'compact'],
    'reduced': ['decreased', 'lowered', 'cut', 'minimized', 'scaled back'],
    'decreased': ['reduced', 'lowered', 'dropped', 'fallen', 'diminished'],
    'lowered': ['reduced', 'decreased', 'dropped', 'cut', 'brought down'],
    'increased': ['raised', 'grown', 'expanded', 'boosted', 'amplified'],
    'raised': ['increased', 'boosted', 'elevated', 'lifted', 'heightened'],
    'grown': ['expanded', 'increased', 'developed', 'extended', 'matured'],
    'expanded': ['grown', 'increased', 'extended', 'broadened', 'widened'],
    'extended': ['expanded', 'lengthened', 'prolonged', 'stretched', 'continued'],
    'prolonged': ['extended', 'lengthened', 'continued', 'drawn out', 'stretched'],
    'continued': ['extended', 'prolonged', 'maintained', 'kept going', 'carried on'],
    'maintained': ['kept', 'preserved', 'sustained', 'continued', 'upheld'],
    'preserved': ['maintained', 'protected', 'saved', 'kept', 'conserved'],
    'sustained': ['maintained', 'continued', 'kept up', 'supported', 'prolonged'],
    'supported': ['backed', 'endorsed', 'upheld', 'championed', 'advocated'],
    'endorsed': ['supported', 'backed', 'approved', 'championed', 'advocated'],
    'approved': ['endorsed', 'authorized', 'cleared', 'sanctioned', 'OK\'d'],
    'authorized': ['approved', 'cleared', 'permitted', 'sanctioned', 'licensed'],
    'permitted': ['allowed', 'authorized', 'cleared', 'approved', 'enabled'],
    'allowed': ['permitted', 'enabled', 'authorized', 'let', 'granted'],
    'enabled': ['allowed', 'permitted', 'facilitated', 'empowered', 'made possible'],
    'empowered': ['enabled', 'allowed', 'authorized', 'supported', 'freed'],
    'facilitated': ['enabled', 'helped', 'assisted', 'supported', 'made easier'],
    'assisted': ['helped', 'supported', 'aided', 'backed', 'guided'],
    'helped': ['assisted', 'aided', 'supported', 'facilitated', 'guided'],
    'aided': ['helped', 'assisted', 'supported', 'backed', 'facilitated'],
    'guided': ['directed', 'led', 'assisted', 'helped', 'steered'],
    'directed': ['guided', 'led', 'steered', 'managed', 'pointed'],
    'led': ['guided', 'directed', 'headed', 'managed', 'ran'],
    'steered': ['guided', 'directed', 'navigated', 'piloted', 'managed'],
    'managed': ['handled', 'directed', 'ran', 'oversaw', 'coordinated'],
    'oversaw': ['managed', 'supervised', 'directed', 'ran', 'headed'],
    'supervised': ['oversaw', 'managed', 'directed', 'monitored', 'ran'],
    'monitored': ['watched', 'tracked', 'observed', 'supervised', 'checked'],
    'tracked': ['monitored', 'followed', 'watched', 'traced', 'kept tabs on'],
    'followed': ['tracked', 'pursued', 'chased', 'went after', 'kept up with'],
    'pursued': ['followed', 'chased', 'went after', 'sought', 'hunted'],
    'sought': ['pursued', 'looked for', 'searched for', 'went after', 'chased'],
    'searched': ['looked for', 'sought', 'hunted for', 'explored', 'investigated'],
    'investigated': ['explored', 'examined', 'looked into', 'probed', 'researched'],
    'explored': ['investigated', 'examined', 'looked into', 'probed', 'discovered'],
    'examined': ['investigated', 'explored', 'analyzed', 'inspected', 'reviewed'],
    'analyzed': ['examined', 'investigated', 'studied', 'reviewed', 'evaluated'],
    'evaluated': ['assessed', 'analyzed', 'judged', 'reviewed', 'appraised'],
    'assessed': ['evaluated', 'judged', 'estimated', 'appraised', 'rated'],
    'reviewed': ['examined', 'analyzed', 'evaluated', 'assessed', 'checked'],
    'studied': ['examined', 'analyzed', 'investigated', 'researched', 'looked into'],
    'researched': ['studied', 'investigated', 'explored', 'examined', 'looked into'],
    'considered': ['thought about', 'weighed', 'pondered', 'contemplated', 'evaluated'],
    'contemplated': ['considered', 'pondered', 'thought about', 'reflected on', 'mused on'],
    'pondered': ['considered', 'contemplated', 'thought about', 'reflected on', 'weighed'],
    'reflected': ['considered', 'pondered', 'thought about', 'contemplated', 'weighed'],
    'weighed': ['considered', 'evaluated', 'pondered', 'contemplated', 'thought about'],
    'evaluated': ['assessed', 'judged', 'analyzed', 'weighed', 'appraised'],
    'judged': ['evaluated', 'assessed', 'determined', 'decided', 'concluded'],
    'determined': ['decided', 'established', 'concluded', 'figured out', 'resolved'],
    'decided': ['determined', 'concluded', 'resolved', 'chose', 'settled on'],
    'concluded': ['decided', 'determined', 'resolved', 'finished', 'wrapped up'],
    'resolved': ['decided', 'determined', 'settled', 'concluded', 'worked out'],
    'settled': ['resolved', 'decided', 'concluded', 'agreed on', 'worked out'],
    'agreed': ['concurred', 'approved', 'accepted', 'consented', 'settled on'],
    'accepted': ['agreed to', 'approved', 'embraced', 'acknowledged', 'went along with'],
    'rejected': ['turned down', 'declined', 'denied', 'dismissed', 'refused'],
    'declined': ['turned down', 'rejected', 'refused', 'dismissed', 'denied'],
    'denied': ['rejected', 'refused', 'declined', 'turned down', 'blocked'],
    'refused': ['rejected', 'declined', 'denied', 'turned down', 'said no to'],
    'dismissed': ['rejected', 'ignored', 'brushed off', 'waved off', 'cast aside'],
    'ignored': ['dismissed', 'overlooked', 'neglected', 'bypassed', 'skipped'],
    'overlooked': ['ignored', 'missed', 'neglected', 'skipped', 'passed over'],
    'neglected': ['ignored', 'overlooked', 'failed to', 'skipped', 'forgot about'],
    'missed': ['overlooked', 'skipped', 'missed', 'failed to catch', 'didn\'t see'],
    'avoided': ['dodged', 'sidestepped', 'steered clear of', 'stayed away from', 'evaded'],
    'evaded': ['avoided', 'dodged', 'sidestepped', 'escaped', 'skirted'],
    'dodged': ['avoided', 'evaded', 'sidestepped', 'skipped', 'skirted'],
    'encouraged': ['urged', 'pushed', 'motivated', 'inspired', 'spurred'],
    'inspired': ['motivated', 'encouraged', 'spurred', 'moved', 'drove'],
    'motivated': ['inspired', 'encouraged', 'drove', 'pushed', 'spurred'],
    'urged': ['encouraged', 'pushed', 'prompted', 'pressed', 'pressured'],
    'prompted': ['triggered', 'caused', 'sparked', 'led to', 'brought about'],
    'triggered': ['prompted', 'caused', 'sparked', 'set off', 'brought about'],
    'caused': ['led to', 'brought about', 'resulted in', 'triggered', 'prompted'],
    'resulted': ['led to', 'caused', 'brought about', 'produced', 'ended up'],
    'produced': ['created', 'generated', 'yielded', 'resulted in', 'turned out'],
    'generated': ['produced', 'created', 'yielded', 'brought about', 'sparked'],
    'yielded': ['produced', 'generated', 'resulted in', 'brought about', 'delivered'],
    'delivered': ['produced', 'provided', 'brought', 'handed over', 'supplied'],
    'provided': ['supplied', 'gave', 'offered', 'delivered', 'furnished'],
    'supplied': ['provided', 'furnished', 'gave', 'delivered', 'offered'],
    'offered': ['proposed', 'presented', 'suggested', 'gave', 'put forward'],
    'proposed': ['suggested', 'offered', 'put forward', 'recommended', 'pitched'],
    'suggested': ['proposed', 'recommended', 'offered', 'advised', 'put forward'],
    'recommended': ['suggested', 'advised', 'proposed', 'endorsed', 'urged'],
    'advised': ['recommended', 'suggested', 'counseled', 'guided', 'urged'],
    'counseled': ['advised', 'guided', 'recommended', 'suggested', 'coached'],
    'instructed': ['directed', 'told', 'guided', 'taught', 'trained'],
    'trained': ['taught', 'coached', 'instructed', 'prepared', 'developed'],
    'taught': ['trained', 'instructed', 'educated', 'coached', 'showed'],
    'educated': ['taught', 'trained', 'informed', 'briefed', 'schooled'],
    'informed': ['told', 'notified', 'briefed', 'updated', 'advised'],
    'notified': ['informed', 'told', 'alerted', 'updated', 'briefed'],
    'updated': ['informed', 'notified', 'refreshed', 'revised', 'brought up to speed'],
    'briefed': ['informed', 'notified', 'updated', 'told', 'filled in'],
    'alerted': ['notified', 'warned', 'informed', 'told', 'flagged'],
    'warned': ['alerted', 'cautioned', 'advised', 'told', 'flagged'],
    'cautioned': ['warned', 'advised', 'alerted', 'reminded', 'told'],
    'reminded': ['told', 'prompted', 'notified', 'alerted', 'flagged'],
}


def get_random_safe_synonym(word: str) -> str | None:
    """Return a random synonym for the word, or None if not found."""
    key = word.lower()
    synonyms = SYNONYM_MAP.get(key)
    if synonyms:
        return random.choice(synonyms)
    return None